
package com.bc.server.code.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BasicCalculatorWS", targetNamespace = "http://ws.code.server.bc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasicCalculatorWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "square", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Square")
    @ResponseWrapper(localName = "squareResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.SquareResponse")
    public int square(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.SubtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.MultiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.DivideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cube", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.Cube")
    @ResponseWrapper(localName = "cubeResponse", targetNamespace = "http://ws.code.server.bc.com/", className = "com.bc.server.code.ws.CubeResponse")
    public int cube(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
