
package com.bc.server.code.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicCalculatorService", targetNamespace = "http://ws.code.server.bc.com/", wsdlLocation = "http://localhost:8080/BasicCalculatorJax-WsServerCodeWithDocumentStyleJB/BasicCalculatorService?wsdl")
public class BasicCalculatorService
    extends Service
{

    private final static URL BASICCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICCALCULATORSERVICE_EXCEPTION;
    private final static QName BASICCALCULATORSERVICE_QNAME = new QName("http://ws.code.server.bc.com/", "BasicCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BasicCalculatorJax-WsServerCodeWithDocumentStyleJB/BasicCalculatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICCALCULATORSERVICE_WSDL_LOCATION = url;
        BASICCALCULATORSERVICE_EXCEPTION = e;
    }

    public BasicCalculatorService() {
        super(__getWsdlLocation(), BASICCALCULATORSERVICE_QNAME);
    }

    public BasicCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICCALCULATORSERVICE_QNAME, features);
    }

    public BasicCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, BASICCALCULATORSERVICE_QNAME);
    }

    public BasicCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICCALCULATORSERVICE_QNAME, features);
    }

    public BasicCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BasicCalculatorWS
     */
    @WebEndpoint(name = "BasicCalculatorPort")
    public BasicCalculatorWS getBasicCalculatorPort() {
        return super.getPort(new QName("http://ws.code.server.bc.com/", "BasicCalculatorPort"), BasicCalculatorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicCalculatorWS
     */
    @WebEndpoint(name = "BasicCalculatorPort")
    public BasicCalculatorWS getBasicCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.code.server.bc.com/", "BasicCalculatorPort"), BasicCalculatorWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICCALCULATORSERVICE_EXCEPTION!= null) {
            throw BASICCALCULATORSERVICE_EXCEPTION;
        }
        return BASICCALCULATORSERVICE_WSDL_LOCATION;
    }

}
