
package com.server.code.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://ws.code.server.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.AddResponse")
    @Action(input = "http://ws.code.server.com/Calculator/addRequest", output = "http://ws.code.server.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.DivideResponse")
    @Action(input = "http://ws.code.server.com/Calculator/divideRequest", output = "http://ws.code.server.com/Calculator/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.SubtractResponse")
    @Action(input = "http://ws.code.server.com/Calculator/subtractRequest", output = "http://ws.code.server.com/Calculator/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ws.code.server.com/", className = "com.server.code.ws.MultiplyResponse")
    @Action(input = "http://ws.code.server.com/Calculator/multiplyRequest", output = "http://ws.code.server.com/Calculator/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
