
package com.employee.server.code;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeCrudService", targetNamespace = "http://code.server.employee.com/", wsdlLocation = "http://localhost:8080/MavenEmployeeCrudJax-WsServerCodeWithRpcStyleJB/EmployeeCrudService?wsdl")
public class EmployeeCrudService
    extends Service
{

    private final static URL EMPLOYEECRUDSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEECRUDSERVICE_EXCEPTION;
    private final static QName EMPLOYEECRUDSERVICE_QNAME = new QName("http://code.server.employee.com/", "EmployeeCrudService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MavenEmployeeCrudJax-WsServerCodeWithRpcStyleJB/EmployeeCrudService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEECRUDSERVICE_WSDL_LOCATION = url;
        EMPLOYEECRUDSERVICE_EXCEPTION = e;
    }

    public EmployeeCrudService() {
        super(__getWsdlLocation(), EMPLOYEECRUDSERVICE_QNAME);
    }

    public EmployeeCrudService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEECRUDSERVICE_QNAME, features);
    }

    public EmployeeCrudService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEECRUDSERVICE_QNAME);
    }

    public EmployeeCrudService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEECRUDSERVICE_QNAME, features);
    }

    public EmployeeCrudService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeCrudService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeWS
     */
    @WebEndpoint(name = "EmployeeCrudPort")
    public EmployeeWS getEmployeeCrudPort() {
        return super.getPort(new QName("http://code.server.employee.com/", "EmployeeCrudPort"), EmployeeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeWS
     */
    @WebEndpoint(name = "EmployeeCrudPort")
    public EmployeeWS getEmployeeCrudPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://code.server.employee.com/", "EmployeeCrudPort"), EmployeeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEECRUDSERVICE_EXCEPTION!= null) {
            throw EMPLOYEECRUDSERVICE_EXCEPTION;
        }
        return EMPLOYEECRUDSERVICE_WSDL_LOCATION;
    }

}
